using System.Collections.Generic;

namespace Trinity.Framework.Objects.Memory.Symbols
{
    public static class SymbolTableNames
    {
        public static Dictionary<int, string> SymbolTableNamesByIndex = new Dictionary<int, string>
        {
            { 0, "KanaiRecipeType"},
            { 1, "SpecialItemType"},
            { 2, "AffixType"},
            { 6, "MaterialType"},
            { 7, "LightingType"},
            { 8, "KeyboardKey"},
            { 9, "WeaponsComboType"},
            { 10, "BonusType"},
            { 11, "GameBalanceType"},
            { 12, "ClothingType"},
            { 14, "ArmorType"},
            { 15, "MonsterType"},
            { 16, "MonsterRace"},
            { 17, "ElementType"},
            { 18, "DamageType"},
            { 19, "HealingType"},
            { 20, "MonsterSize"},
            { 21, "MonsterQuality"},
            { 22, "ActType"},
            { 23, "VendorSlot"},
            { 24, "ItemQuality"},
            { 25, "GemType"},
            { 30, "ResourceType"},
            { 31, "DensityType"},
            { 32, "SoundEffectType"},
            { 33, "SoundAdjustmentType"},
            { 34, "CurveType"},
            { 35, "ShapeType"},
            { 36, "StuckFlags"},
            { 37, "DifficultyType"},
            { 38, "DifficultyLevel"},
            { 39, "NpcType"},
            { 40, "CurrencyType"},
            { 41, "ItemResult"},
            { 43, "CollisionResult"},
            { 44, "QuestStepType"},
            { 45, "QuestResult"},
            { 46, "QuestType"},
            { 47, "BountyType"},
            { 48, "EventType"},
            { 50, "RecipeType"},
            { 51, "PathType"},
            { 52, "ErrorResultType"},
            { 53, "AmbientType"},
            { 54, "ConversationType"},
            { 55, "FollowerType"},
            { 56, "ComparisonType"},
            { 57, "AdjustmentType"},
            { 63, "ActorClass"},
            { 65, "ActorType"},
            { 67, "NodeFlags"},
            { 68, "ParagonType"},
            { 69, "ActorState"},
            { 71, "RuneSlot" },
            { 72, "MonsterQuality2"},
            { 73, "GizmoType"},
            { 74, "InventorySlot"},
            { 75, "ConsumableType"},
            { 79, "D3ItemType"},
            { 80, "PlayerAttribute"},
            { 81, "PetType"},
            { 82, "SpecialBonus"},
            { 83, "LeaveGameResult"},
            { 86, "AnimationType"},
            { 87, "AnimationTransitionType"},
            { 88, "MovementAttributeType"},
            { 91, "ValueDataType"},
            { 92, "PlayerStateFlags"},
            { 93, "IdentifierType"},
        };
    }
}