namespace Trinity.Framework.Objects.Memory.Symbols.Types
{
    public enum GizmoType // 2.4.0.36090 @26706328 index:73
    {
        Unknown = -1,
        Door = 0,
        BreakableDoor = 56,
        Chest = 1,
        Sign = 8,
        Portal = 2,
        PortalDestination = 20,
        Waypoint = 4,
        HealingWell = 9,
        PowerUp = 10,
        TownPortal = 11,
        HearthPortal = 12,
        Headstone = 18,
        BreakableChest = 23,
        SharedStash = 25,
        Spawner = 28,
        Trigger = 44,
        SecretPortal = 47,
        DestroyableObject = 48,
        Checkpoint = 7,
        Switch = 57,
        LootRunSwitch = 78,
        PressurePlate = 58,
        Gate = 59,
        DestroySelfWhenNear = 60,
        ActTransitionObject = 62,
        ReformingDestroyableObject = 63,
        Banner = 64,
        LoreChest = 65,
        BossPortal = 66,
        PlacedLoot = 67,
        SavePoint = 68,
        ReturnPointPortal = 69,
        DungeonPortal = 70,
        ReturnPortal = 75,
        PageOfFatePortal = 33,
        IdentifyAll = 71,
        RecreateGameWithParty = 76,
        Mailbox = 77,
        PoolOfReflection = 79,
        MultiClick = 80,
        ObjectiveFinder = 82,
    }
}