namespace Trinity.UIComponents
{
    public enum ItemProperty
    {
        Unknown = 0,
        LifePercent = 1,
        Armor = 2,
        CriticalHitChance = 3,
        CriticalHitDamage = 4,
        SkillDamage = 5,
        LifePerSpirit = 6,
        Dexterity = 7,
        Strength = 8,
        Intelligence = 9,
        Vitality = 10,
        AreaDamage = 11,
        Cooldown = 12,
        ResourceCost = 13,
        Durability = 14,
        ResistPhysical = 15,
        ResistCold = 16,
        ResistFire = 17,
        ResistLightning = 18,
        ResistArcane = 19,
        ResistPoison = 20,
        ExtraGold = 21,
        Thorns = 22,
        HealthPickup = 23,
        ChanceToChill = 24,
        IgnoresDurability = 25,
        PotionsGrantHealth = 26,
        LevelRequirement = 27,
        MovementSpeed = 28,
        ResistAll = 29,
        MonsterKillsGrantExp = 30,
        ChanceToImmobilize = 31,
        ChanceToBlind = 32,
        ReduceControlEffects = 33,
        ColdSkills = 34,
        FireSkills = 35,
        HolySkills = 36,
        LightningSkills = 37,
        PoisonSkills = 38,
        PhysicalSkills = 39,
        WrathRegen = 40,
        AttackSpeed = 41,
        LifePerHit = 42,
        DamageFromElites = 43,
        ChanceToBleed = 44,
        HatredRegen = 45,
        Sockets = 46,
        BaseMaxDamage = 47,
        LifePerWrath = 48,
        DamageAgainstElites = 49,
        LifePerFury = 50,
        SpiritRegen = 51,
        MaximumWrath = 52,
        LifeAfterKill = 53,
        MaximumMana = 54,
        MaximumArcane = 55,
        DamageFromMelee = 56,
        DamageFromRanged = 57,
        MaximumSpirit = 58,
        MaximumFury = 59,
        ChanceToBlock = 60,
        ChanceToFear = 61,
        ChanceToStun = 62,
        ChanceToFreeze = 63,
        ChanceToSlow = 64,
        ChanceToKnockback = 65,
        RegenerateLifePerSecond = 66,
        MaximumDiscipline = 67,
        CriticalHitsGrantArcane = 68,
        ArcaneSkills = 69,
        ManaRegen = 70,
        PercentDamage = 71,
        Ancient = 72,
        PrimaryStat = 73,
        ElementalDamage = 74,
        ElementalResist,
        ChanceToBlockTotal,
        PassivePower
    }
}

