namespace Trinity.Framework.Objects.Memory.Symbols.Types
{
    public enum ConsumableType // 2.4.0.36090 @26706864 index:75
    {
        None = 0,
        HealthPotion = 1,
        TownPortalStone = 3,
        TownPortalUnlock = 54,
        HearthPortalScroll = 24,
        CalldownGrenade = 6,
        PageofFate = 21,
        HealthGlyph = 25,
        Scroll = 28,
        ManaGlyph = 31,
        ArcaneGlyph = 50,
        Dye = 32,
        DyeReusable = 57,
        LearnEnchant = 38,
        LearnRecipe = 39,
        SummonMonster = 46,
        SummonCompanion = 48,
        PageofTraining = 53,
        PowerUpGlyph = 55,
        CollectorsEditionBuff = 56,
        PortalScroll = 19,
        PowerScroll = 20,
        EnchantScroll = 58,
        ShrineGlyph = 59,
        UnlockTransmogs = 60,
        TreasureBag = 61,
        PlayerGift = 62,
        AddSockets = 63,
        LootRunProgressGlyph = 64,
        LearnWings = 65,
        LearnPet = 67,
        LearnPortraitFrame = 68,
        LearnPennant = 69,
        HoradricReagent = 70,
    }
}