namespace Trinity.Framework.Objects.Memory.Misc
{
    //public enum GameBalanceType // 2.4.0.36090 @26700352 index:11
    //{
    //    ItemTypes = 1,
    //    Items = 2,
    //    ExperienceTable = 3,
    //    HelpCodes = 24,
    //    MonsterLevels = 5,
    //    Heros = 7,
    //    AffixList = 8,
    //    MovementStyles = 10,
    //    Labels = 11,
    //    LootDistribution = 12,
    //    RareItemNames = 16,
    //    MonsterAffixes = 18,
    //    MonsterNames = 19,
    //    SocketedEffects = 21,
    //    ItemDropTable = 25,
    //    ItemLevelModifiers = 26,
    //    QualityClasses = 27,
    //    Handicaps = 28,
    //    ItemSalvageLevels = 29,
    //    Scenery = 17,
    //    Hirelings = 4,
    //    SetItemBonuses = 33,
    //    EliteModifiers = 34,
    //    ItemTiers = 35,
    //    PowerFormulaTables = 36,
    //    Recipes = 32,
    //    ScriptedAchievementEvents = 37,
    //    LootRunQuestTiers = 39,
    //    ParagonBonuses = 40,
    //    LegacyItemConversions = 45,
    //    EnchantItemAffixUseCountCostScalars = 46,
    //    TieredLootRunLevels = 49,
    //    TransmuteRecipes = 50,
    //}
}