namespace Trinity.Framework.Objects.Memory.Misc
{
    public enum WeaponsComboType // 2.4.0.36090 @26699984 index:9
    {
        None = -1,
        Handtohand = 0,
        OneHSwing = 1,
        OneHThrust = 2,
        OneHFist = 15,
        TwoHSwing = 3,
        TwoHAxeMace = 16,
        TwoHFlail = 25,
        TwoHThrust = 4,
        Staff = 5,
        Bow = 6,
        Crossbow = 7,
        Wand = 8,
        DualWield = 9,
        DualWieldSf = 13,
        DualWieldFf = 14,
        HtHwOrb = 10,
        OneHSwOrb = 11,
        OneHTwOrb = 12,
        WandwOrb = 18,
        HandXBow = 17,
        OneHSwingwShield = 19,
        OneHThrustwShield = 20,
        HthwShield = 21,
        TwoHSwingwShield = 22,
        TwoHThrustwShield = 23,
        TwoHFlailwShield = 26,
        StaffwShield = 24,
        OnHorse = 27,
    }
}