namespace Trinity.Framework.Avoidance
{
    public enum AvoidanceType
    {
        None = 0,
        DiseaseCloud,
        ZultunKuleTornado,
        OrlashBoss,
        Thunderstorm,
        HeraldOfPestilence,
        Desecrator,
        MorluMeteor,
        ExarchLightningStorm,
        GhomBoss,
        MoltenCore,
        FireChains,
        TethrysBoss,
        Frozen,
        Furnace,
        ButcherBoss,
        Grotesque,
        ChargeAttacks,
        RatKing,
        Plagued,
        FrozenPulse,
        MoltenTrail,
        ArcaneSentry,
        MaghdaBoss,
        Orbiter,
        MageFire,
        PoisonEnchanted,
        Mortar,
        MalthaelTeleport,
        PerendiDefaultAttack,
        MalthaelDeathFog,
        MalthaelHellGates,
        Urzael
    }
}